addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libpng-dev
    - libxml-parser-perl
    - libxtst-dev
    - xutils-dev
script:
- ./bootstrap.sh manifest.txt
deploy:
  provider: releases
  api_key:
    secure: OVAy1CWVr2ISBLPwv5mUDBIyQoY4OnnbF6xXVXugpSP2/oL70+c64z9GjxgTiChMTvZ6Jr5DzZbkFPNeyV2u+XdVNidv+0GecjRU2UAXVv0AgNumraBKGkaxtyQKAntYgk8FmhdbJ4xQjADcSrhIimLsdJ2qsyULpAeUU1CK3OgUzbcU5OYoETQHPVuLPnZtvrubIRmktIeRoDcL3NUe4ntngWb5o3g/f367PJ+kLGR4d7OjWQ2Q/k1oaBbzKIFsB4oQoGcZjkDtqQROtlsqlXmO+Q8Nv4ZOyEu/AV+3SsyEdwhGlTC02WLaq3wdBx3engygNebzFVI3u4Nz6rJ4VSbBXyBfDqTZrKUlgr55Hzncl/4ocofEp7lr2u0GGvQzgCWsvnUAO7mfGZW7SD5FZQmqbhNbZOgGVFO5EC1NpU83G0+UMwADgkywAPOwXzwlaOzq5N3mkm10vhAMbh4sVmP+ZnUGBgPvCVHQqDXN2djRi38V3F9MgwPgBlI/pX9QcVy6sLSuvtros3+mcwG7uAv/e8tq35jGwu4WVTs8XjHb4FSFNPVPf1IAvUwFJEBERdUcLh/QJrkGMTeyelGZG3cwZtr/Y0cSwmAE36rMr00zaB5KfCfJNBougpi6Fo0zrvektgkpBcg/VyfIj1gey6DcPOIzpi/QhjpsFcaO0Q0=
  file: deps.txz
  skip_cleanup: true
  on:
    tags: true
